// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYopFtHEaajSBwWJ8WjVhEvBcBg9NRMQ',
    appId: '1:123107177476:web:56dcec43decf38cfc43151',
    messagingSenderId: '123107177476',
    projectId: 'expensetracker-70785',
    authDomain: 'expensetracker-70785.firebaseapp.com',
    storageBucket: 'expensetracker-70785.firebasestorage.app',
    measurementId: 'G-K04DW57K7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bZ6duchEsATKjMCM-evP8wAj8mRrgXg',
    appId: '1:123107177476:android:3326b3280caa0221c43151',
    messagingSenderId: '123107177476',
    projectId: 'expensetracker-70785',
    storageBucket: 'expensetracker-70785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvSpzUdD-GRpggUt6fgd4hwFqV4PTX2Q',
    appId: '1:123107177476:ios:acf05f09f643f7c2c43151',
    messagingSenderId: '123107177476',
    projectId: 'expensetracker-70785',
    storageBucket: 'expensetracker-70785.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmvSpzUdD-GRpggUt6fgd4hwFqV4PTX2Q',
    appId: '1:123107177476:ios:acf05f09f643f7c2c43151',
    messagingSenderId: '123107177476',
    projectId: 'expensetracker-70785',
    storageBucket: 'expensetracker-70785.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSYopFtHEaajSBwWJ8WjVhEvBcBg9NRMQ',
    appId: '1:123107177476:web:bcba0ae7a82db8dfc43151',
    messagingSenderId: '123107177476',
    projectId: 'expensetracker-70785',
    authDomain: 'expensetracker-70785.firebaseapp.com',
    storageBucket: 'expensetracker-70785.firebasestorage.app',
    measurementId: 'G-51H2GYLVBW',
  );

}